name: Sheenam Build Pipeline
on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Setting Up Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202
        include-prerelease: false
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
